"""Extract executable Python code from raw LLM output.

Implements subject section V.1.2: the agent must accept several tool
-calling formats a model might have been trained on -- not just fenced
Python blocks -- and convert every non-Python format into an
equivalent Python function call before it reaches the sandbox. This
keeps the sandbox itself format-agnostic.

Every extraction result is an ``ExtractionResult``, which always
carries a ``note`` explaining what happened -- including the "no code
found" / "malformed block interpreted anyway" cases the subject
explicitly calls out, so the LLM is never met with silent, unexplained
behaviour.
"""
import ast
import json
import re
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class ExtractionResult:
    """Outcome of extracting code from one LLM response.

    Attributes:
        code: The Python source to execute, or ``""`` if nothing
            usable was found.
        found: Whether *any* recognizable code/tool-call was found.
        format_used: Which format matched ("python", "xml_invoke",
            "json_tool_call", "react", or "none").
        note: A human-readable explanation always included in the
            sandbox_input logged for this step, and prepended as a
            comment to `code` when it documents a fallback/malformed
            case, so the LLM sees exactly what happened.
    """

    code: str
    found: bool
    format_used: str
    note: str = ""


_PYTHON_BLOCK_RE = re.compile(
    r"```(?:python|py)?\s*\n(.*?)```", re.DOTALL | re.IGNORECASE
)
_XML_INVOKE_RE = re.compile(
    r"<invoke\s+name=[\"']([^\"']+)[\"']>(.*?)</invoke>", re.DOTALL
)
_XML_PARAM_RE = re.compile(
    r"<parameter\s+name=[\"']([^\"']+)[\"']>(.*?)</parameter>", re.DOTALL
)
_JSON_TOOL_CALL_RE = re.compile(
    r"<tool_call>\s*(\{.*?\})\s*</tool_call>", re.DOTALL
)
_REACT_RE = re.compile(
    r"Action:\s*([\w\.]+)\s*\n\s*Action Input:\s*(\{.*?\})",
    re.DOTALL,
)


def _python_repr_of_json_value(value: object) -> str:
    """Render a JSON-decoded value as a Python literal for a call arg."""
    return repr(value)


def _xml_invoke_to_python(name: str, body: str) -> str:
    """Convert one <invoke>...</invoke> block into a Python call."""
    params = _XML_PARAM_RE.findall(body)
    args: List[str] = []
    for pname, pvalue in params:
        value = pvalue.strip()
        # Anthropic-style XML tool calls pass everything as text;
        # try to recover ints/floats/bools/JSON, else keep as string.
        try:
            parsed = json.loads(value)
            args.append(f"{pname}={_python_repr_of_json_value(parsed)}")
        except (json.JSONDecodeError, ValueError):
            args.append(f"{pname}={value!r}")
    return f"result = {name}({', '.join(args)})\nprint(result)"


def _json_tool_call_to_python(payload: dict) -> Optional[str]:
    """Convert a Hermes-style {"name": ..., "arguments": {...}} dict."""
    name = payload.get("name")
    if not name:
        return None
    arguments = payload.get("arguments", {}) or {}
    if not isinstance(arguments, dict):
        return None
    args = ", ".join(
        f"{k}={_python_repr_of_json_value(v)}" for k, v in arguments.items()
    )
    return f"result = {name}({args})\nprint(result)"


def extract_code(llm_output: str) -> ExtractionResult:
    """Extract executable Python code from one LLM response.

    Tries, in order: fenced Python code blocks (primary format),
    Anthropic-style XML ``<invoke>`` tool calls, JSON/Hermes
    ``<tool_call>`` blocks, and ReAct ``Action:``/``Action Input:``
    pairs. The first format that matches wins; non-Python formats are
    converted to an equivalent ``result = tool(...)`` call.

    Args:
        llm_output: The raw text generated by the LLM for this step.

    Returns:
        ExtractionResult: Always populated, even when nothing was
        found -- see ``ExtractionResult.note`` for what happened.
    """
    if not llm_output or not llm_output.strip():
        return ExtractionResult(
            code="",
            found=False,
            format_used="none",
            note=(
                "No text was generated by the model for this step "
                "(empty response)."
            ),
        )

    # 1. Python code blocks (primary format).
    python_blocks = _PYTHON_BLOCK_RE.findall(llm_output)
    if python_blocks:
        code = "\n".join(block.strip() for block in python_blocks)
        try:
            ast.parse(code)
            return ExtractionResult(
                code=code, found=True, format_used="python"
            )
        except SyntaxError as e:
            note = (
                f"A ```python``` block was found but is not valid "
                f"Python (SyntaxError: {e}). It is being sent to the "
                "sandbox anyway -- the resulting traceback is your "
                "real Observation for this step, use it to fix the "
                "syntax on your next attempt."
            )
            return ExtractionResult(
                code=code, found=True, format_used="python", note=note
            )

    # 2. Anthropic-style XML tool calls.
    xml_matches = _XML_INVOKE_RE.findall(llm_output)
    if xml_matches:
        calls = [
            _xml_invoke_to_python(name, body) for name, body in xml_matches
        ]
        code = "\n".join(calls)
        return ExtractionResult(
            code=code,
            found=True,
            format_used="xml_invoke",
            note=(
                "No ```python``` block was found, but an XML "
                "<invoke> tool call was -- it was converted to an "
                f"equivalent Python call:\n{code}"
            ),
        )

    # 3. JSON / Hermes-style tool calls.
    json_matches = _JSON_TOOL_CALL_RE.findall(llm_output)
    if json_matches:
        converted: List[str] = []
        for raw in json_matches:
            try:
                payload = json.loads(raw)
            except json.JSONDecodeError as e:
                return ExtractionResult(
                    code="",
                    found=False,
                    format_used="json_tool_call",
                    note=(
                        "A <tool_call> block was found but its JSON "
                        f"payload could not be parsed ({e}). Re-emit "
                        "a single, valid JSON object inside "
                        "<tool_call>...</tool_call>."
                    ),
                )
            call = _json_tool_call_to_python(payload)
            if call:
                converted.append(call)
        if converted:
            code = "\n".join(converted)
            return ExtractionResult(
                code=code,
                found=True,
                format_used="json_tool_call",
                note=(
                    "No ```python``` block was found, but a "
                    "<tool_call> JSON payload was -- it was converted "
                    f"to an equivalent Python call:\n{code}"
                ),
            )

    # 4. ReAct format.
    react_match = _REACT_RE.search(llm_output)
    if react_match:
        tool_name, raw_args = react_match.groups()
        try:
            arguments = json.loads(raw_args)
        except json.JSONDecodeError as e:
            return ExtractionResult(
                code="",
                found=False,
                format_used="react",
                note=(
                    "An 'Action:'/'Action Input:' pair was found but "
                    f"'Action Input' is not valid JSON ({e}). Re-emit "
                    "it as a single JSON object."
                ),
            )
        args = ", ".join(
            f"{k}={_python_repr_of_json_value(v)}"
            for k, v in arguments.items()
        )
        code = f"result = {tool_name}({args})\nprint(result)"
        return ExtractionResult(
            code=code,
            found=True,
            format_used="react",
            note=(
                "No ```python``` block was found, but a ReAct "
                "Action/Action Input pair was -- it was converted to "
                f"an equivalent Python call:\n{code}"
            ),
        )

    # 5. Nothing recognizable at all.
    return ExtractionResult(
        code="",
        found=False,
        format_used="none",
        note=(
            "No valid code block was found in the model's response "
            "(no ```python``` fence, <invoke>, <tool_call>, or "
            "ReAct Action/Action Input pair). Remember to respond "
            "using EXACTLY the required format."
        ),
    )
